#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class StackPanel;
                ref class RelativePanel;
                ref class Grid;
                ref class CheckBox;
                ref class TextBox;
                ref class Slider;
                ref class TextBlock;
                ref class Button;
            }
        }
    }
}
namespace Microsoft {
    namespace Graphics {
        namespace Canvas {
            namespace UI {
                namespace Xaml {
                    ref class CanvasAnimatedControl;
                }
            }
        }
    }
}

namespace Stadium
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::StackPanel^ contentPanel;
        private: ::Microsoft::Graphics::Canvas::UI::Xaml::CanvasAnimatedControl^ canvas;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ inputPanel;
        private: ::Windows::UI::Xaml::Controls::RelativePanel^ buttonPanel;
        private: ::Windows::UI::Xaml::Controls::RelativePanel^ sliderPanel;
        private: ::Windows::UI::Xaml::Controls::RelativePanel^ teamsControlPanel;
        private: ::Windows::UI::Xaml::Controls::RelativePanel^ team1Panel;
        private: ::Windows::UI::Xaml::Controls::RelativePanel^ Team2Panel;
        private: ::Windows::UI::Xaml::Controls::Grid^ PlayersInGameGrid;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ checkBoxT1P2;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ checkBoxT1P3;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ checkBoxT1P4;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ checkBoxT1P5;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ checkBoxT1P6;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ checkBoxT2P2;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ checkBoxT2P3;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ checkBoxT2P4;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ checkBoxT2P5;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ checkBoxT2P6;
        private: ::Windows::UI::Xaml::Controls::TextBox^ textEnergyTeam2;
        private: ::Windows::UI::Xaml::Controls::TextBox^ textScoreTeam2;
        private: ::Windows::UI::Xaml::Controls::TextBox^ textEnergyTeam1;
        private: ::Windows::UI::Xaml::Controls::TextBox^ textScoreTeam1;
        private: ::Windows::UI::Xaml::Controls::Slider^ slider;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ checkBoxPauseShow;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ checkBoxSound;
        private: ::Windows::UI::Xaml::Controls::Button^ startButton;
        private: ::Windows::UI::Xaml::Controls::Button^ stopButton;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlockTime;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlockComent;
    };
}

